#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright © 2014 petrikoz <po.zelenin@gmail.com>
#
# Distributed under terms of the BSD license.
language: python
notifications:
    email: "po.zelenin@gmail.com"
python:
    - "2.7"
install:
    - "pip install ."
    - "pip install nose coverage coveralls pyramid"
script:
    - "make test"
